# Generated by Django 4.0.2 on 2022-03-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
