# Generated by Django 4.0.2 on 2022-03-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_cliente_apellidos_alter_cliente_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario_administrador',
            field=models.BooleanField(default=True),
        ),
    ]
