# Generated by Django 4.0.2 on 2022-03-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_cliente_usuario_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
