# Generated by Django 4.0.3 on 2022-03-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_servicio_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.servicio'),
        ),
    ]
